{
  "hash": "324916620da1edd11712efcd6a387e23",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Data Report\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n---\n\nThis project draws on two complementary data sources to investigate whether gold functions as an inflation hedge through the lens of physical trade flows. UN Comtrade data captures what flows where between countries, while the World Bank Global Inflation Database captures the inflationary environment the country was in at the time. Joining the two on country and year lets us answer the narrative's driving question, *when inflation hit in 2022, who actually bought the gold?*, at the country-year level.\n\nAll raw inputs live under data/raw/. Reproducible build scripts in data/build_dataset.py and data/country_mapping.py generate the processed outputs in data/processed/. The original Kaggle UN Comtrade dump ends in 2016, which was a problem for our 2022 to 2023 inflation-wave question, so we added a second, more recent UN Comtrade extract (1990–2025) midway through the project to extend the coverage.\n\n**Scope of the visible narrative.** The full processed table spans 1988–2024 and ~190 k rows. The scrollytelling app (`deployment/app.py`) restricts the visible analysis to **2017–2024**, because the pre-2017 half of the joined panel is missing major gold-import reporters (Switzerland, USA, UK, UAE; see Processed Dataset 1 below). The full 1988–2024 table remains in `data/processed/` for reproducibility and for any future analysis that does not depend on a complete global panel.\n\n**Metals in scope.** The processed dataset retains Gold, Silver, Platinum, and Other-precious flows. The current narrative is **gold-only**; silver and platinum are kept in the CSV because removing them would mean diverging the build pipeline from the data report, but they are not visible in the app. A future iteration that picks up the gold-vs-peers comparison can read them from the existing file without re-running the build.\n\n## Raw data\n\n### Overview Raw Datasets\n\n: Overview of raw datasets used in the project. {#tbl-raw-overview}\n\n| Name                                   | Source                                                                                  | Storage location                              | Size      |\n|----------------------------------------|------------------------------------------------------------------------------------------|-----------------------------------------------|-----------|\n| UN Comtrade: Global Commodity Trade Statistics (1988–2016)  | Kaggle dataset by Uciml, derived from UN Comtrade                                       | data/raw/commodity_trade_statistics_data.csv | ~1.2 GB   |\n| UN Comtrade: Precious Metals (1990–2025)         | UN Comtrade Database (HS chapter 71 extract, codes 7106–7112)                          | data/raw/comtrade_1990_2025.csv             | ~24 MB    |\n| World Bank Global Inflation Database   | Ha, Kose & Ohnsorge (2023), *One-Stop Source: A Global Database of Inflation*, World Bank | data/raw/Inflation-data.xlsx                | ~5.6 MB   |\n\n### Details Dataset 1\n\n**Content.** Country-level commodity trade statistics from the United Nations Comtrade database, redistributed on Kaggle. Covers virtually every traded commodity (HS classification) for 1988–2016, with import / export / re-import / re-export flows, USD values, weights and physical quantities.\n\n**Source / provider.** Kaggle dataset *\"Global Commodity Trade Statistics\"* by user uciml, derived from the UN Comtrade Database (<https://comtradeplus.un.org>). UN Comtrade itself is maintained by the United Nations Statistics Division.\n\n**Procurement.** Downloaded once from Kaggle via the kagglehub Python package. The file is large (~1.2 GB) and not committed to git; team members re-acquire it with:\n\n```bash\nkagglehub dataset download unstats/global-commodity-trade-statistics\nmv ~/.cache/kagglehub/.../commodity_trade_statistics_data.csv data/raw/\n```\n\n**Legal aspects.** The Kaggle redistribution is published under the Creative Commons CC0 1.0 (public domain) license. The underlying UN Comtrade data is subject to the UN Statistics Division terms of use (free non-commercial use with attribution).\n\n**Data governance.** Public, non-personal, business-relevant aggregate trade statistics. No sensitive or personal data.\n\n**Role in the analysis.** Provides the dependent / target family of variables in our narrative: trade value in USD and weight in kilograms of precious-metals flows.\n\n#### Data Catalogue\n\n: Data catalogue for the UN Comtrade legacy dataset (raw columns kept after filtering to HS 7106–7112). {#tbl-data-catalogue-comtrade}\n\n| # | Column name      | Datatype | Values / validation                                    | Description                                                |\n|---|------------------|----------|---------------------------------------------------------|------------------------------------------------------------|\n| 1 | country_or_area  | string   | 263 country / area names, free-text                     | Reporting country                                          |\n| 2 | year             | int      | 1988 – 2016                                             | Calendar year of the trade flow                            |\n| 3 | comm_code        | string   | HS 6-digit code, here filtered to 7106–7112             | Harmonized System commodity code                           |\n| 4 | commodity        | string   | Free-text commodity description                         | Human-readable commodity name                              |\n| 5 | flow             | category | Import, Export, Re-Import, Re-Export                    | Direction of the trade flow                                |\n| 6 | trade_usd        | int      | ≥ 0, USD                                                | Trade value in current US dollars                          |\n| 7 | weight_kg        | float    | ≥ 0, kg (some missing)                                  | Net weight                                                 |\n| 8 | quantity_name    | string   | e.g. Weight in kilograms, Number of items               | Unit of quantity                                           |\n| 9 | quantity         | float    | ≥ 0                                                     | Physical quantity in the unit above                        |\n| 10 | category        | string   | HS chapter group, e.g. 71_pearls_precious_stones_metals | Aggregated commodity category                              |\n\n#### Data Characteristics and Quality\n\nThe full file has ~8.2 M rows across all commodities. After filtering on commodity descriptions containing \"Gold\", \"Silver\", \"Platinum\" or \"precious metal\" in build_dataset.py, we retain ~190 k rows on HS chapter 71 metals, well above the 500-row course minimum and the right order of magnitude for country–year aggregates.\n\nFindings from EDA:\n\n- **Coverage.** 263 reporting countries or areas, every year from 1988 to 2016. Coverage is densest from the mid-1990s onward. Most early-1990s post-Soviet states only start reporting in 1995 to 1996.\n- **Missing values.** Weight is missing in roughly 11 % of precious-metals rows (small jewellery items reported only as a count). Trade value in USD is never missing.\n- **Zero values.** About 9 % of rows have a zero weight, almost all for fabricated articles (rings, coins) where the reporting country dropped weight reporting.\n- **Skew.** Trade value is strongly right-skewed (median ≈ 73 k USD, max ≈ 97 bn USD, a 2014 Switzerland gold import row). A log scale will be required for any scatter visualization.\n- **Negative values.** None. The raw data is sign-clean.\n- **Commodity cardinality.** Around 25 distinct precious-metals commodity strings. We collapse these into four metal groups (Gold, Silver, Platinum, Other precious) in processing.\n- **Flow imbalance.** Imports dominate the rows (~82 %), reflecting the fact that more countries report imports than exports for HS 71.\n\n::: {#cell-fig-trade-by-metal .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\ntrade = pd.read_csv(\"../data/processed/precious_metals_trade_1988_2024.csv\")\ncounts = trade[\"metal_group\"].value_counts().reindex(\n    [\"Gold\", \"Silver\", \"Platinum\", \"Other precious\"]\n)\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nbars = ax.bar(counts.index, counts.values,\n              color=[\"#D4AF37\", \"#C0C0C0\", \"#7F8C8D\", \"#BDC3C7\"],\n              edgecolor=\"white\")\nax.set_ylabel(\"Number of records\")\nax.set_title(\"Records per metal group\")\nfor s in (\"top\", \"right\"):\n    ax.spines[s].set_visible(False)\nfor bar, val in zip(bars, counts.values):\n    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(),\n            f\"{val:,}\", ha=\"center\", va=\"bottom\", fontsize=9)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/var/folders/yg/7z2hqpxd2q3_f61kw91nbmj00000gn/T/ipykernel_39823/1396133371.py:20: UserWarning: The figure layout has changed to tight\n  plt.tight_layout()\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Number of precious-metals trade records by metal group in the processed dataset (1988–2024).](data_report_files/figure-html/fig-trade-by-metal-output-2.png){#fig-trade-by-metal width=581 height=343}\n:::\n:::\n\n\n**Implications for visualisation.** The heavy right-skew in trade values shaped the design of Beat 2 of the narrative (the inflation-vs-gold-imports comparison). Rather than show a full-panel scatter with a log axis (which would have made small bars artificially legible and softened the visual disconfirmation), we hand-curate Beat 2 to ten named countries plotted on a linear axis. The 11 % missing weights mean we lead with trade value for cross-country comparisons and use weight only as a secondary lens for top reporters where it is dense.\n\n### Details Dataset 2\n\n**Content.** A focused extract from the official UN Comtrade Plus API for HS codes 7106–7112 (silver, gold, platinum, semi-manufactured forms, waste & scrap, coins), covering 1990 to 2025.\n\n**Source / provider.** UN Comtrade Plus (<https://comtradeplus.un.org/>), UN Statistics Division.\n\n**Procurement.** Pulled directly through the UN Comtrade REST API and saved as a single CSV. We added this dataset *after* discovering that the Kaggle dump ended in 2016, which made it impossible to study the 2022–23 inflation spike directly. The newer extract is much narrower than the Kaggle dump (only HS 71 codes, only the BACI / Comtrade harmonized fields) but extends coverage by nine extra years.\n\n**Legal aspects.** UN Comtrade is free for non-commercial use with attribution. Bulk redistribution is permitted under the same terms.\n\n**Data governance.** Public, non-personal.\n\n**Role in the analysis.** Same target variables as Dataset 1 (primary trade value and net weight), used to extend the time series past 2016.\n\n#### Data Catalogue\n\nThe full extract has 46 columns; the ones we retain are listed below. Columns dropped early include estimation flags, customs codes and mode-of-transport metadata that are not relevant for country–year aggregates.\n\n: Retained columns from the UN Comtrade 1990–2025 extract. {#tbl-data-catalogue-comtrade2}\n\n| # | Column name    | Datatype | Values / validation                          | Description                                            |\n|---|----------------|----------|-----------------------------------------------|--------------------------------------------------------|\n| 1 | refYear        | int      | 1990 – 2025                                   | Reference year                                         |\n| 2 | reporterISO    | string   | ISO-3 code, e.g. AUS                          | Reporting country code                                 |\n| 3 | reporterDesc   | string   | Country name                                  | Reporting country, free-text                           |\n| 4 | flowCode       | category | M, X, RM, RX                                  | Import / Export / Re-Import / Re-Export                |\n| 5 | partnerISO     | string   | ISO-3 code or W00 (World)                     | Trade partner code                                     |\n| 6 | cmdCode        | string   | HS codes 7106 – 7112                          | HS commodity code                                      |\n| 7 | cmdDesc        | string   | HS description                                | Free-text commodity description                        |\n| 8 | netWgt         | float    | ≥ 0, kg, may be empty                         | Net weight                                             |\n| 9 | primaryValue   | float    | ≥ 0, USD                                      | Primary trade value (CIF for imports, FOB for exports) |\n| 10 | qty           | float    | ≥ 0                                           | Reported physical quantity                             |\n\n#### Data Characteristics and Quality\n\n71,843 rows for HS 7106–7112 globally. ISO codes are clean (no manual fuzzy matching needed). The 2017 to 2025 portion is the main reason this dataset exists. Earlier years overlap with Dataset 1 but use slightly different harmonisation revisions, so we do not stack the two raw files: Dataset 1 provides 1988 to 2016 and Dataset 2 provides 2017 to 2024 in the merged output.\n\n### Details Dataset 3\n\n**Content.** Country-level inflation rates by indicator (Headline CPI, Food CPI, Energy CPI, Core CPI, PPI, GDP deflator), at monthly, quarterly and annual frequency. We use only the annual sheets for joining with annual trade data.\n\n**Source / provider.** Ha, J., Kose, M. A., & Ohnsorge, F. (2023). *One-Stop Source: A Global Database of Inflation* (Policy Research Working Paper 10493). World Bank Group. Hosted at <https://www.worldbank.org/en/research/brief/inflation-database>.\n\n**Procurement.** Manually downloaded once from the World Bank brief page as Inflation-data.xlsx and committed to data/raw/. The file is small enough (~5.6 MB) that we keep it in the repo for easy reproducibility.\n\n**Legal aspects.** World Bank data is released under the Creative Commons CC-BY 4.0 license. Attribution to Ha, Kose & Ohnsorge (2023) is required and given in the references.\n\n**Data governance.** Public, non-personal, official macroeconomic statistics.\n\n**Role in the analysis.** Provides the *independent / regressor* variables: country-year inflation rates. We use Headline CPI as the primary driver and Food / Energy / Core CPI as secondary lenses to answer research question 5 (*\"Which type of inflation has the strongest link to gold trade activity?\"*).\n\n#### Data Catalogue\n\nThe Excel workbook contains 20 sheets. Each annual sheet (hcpi_a, fcpi_a, ecpi_a, ccpi_a, ppi_a, def_a) is one wide table with year columns 1970–2024.\n\n: Structure of one annual inflation sheet (e.g. hcpi_a). {#tbl-data-catalogue-inflation}\n\n| # | Column name      | Datatype | Values / validation                            | Description                                          |\n|---|------------------|----------|------------------------------------------------|------------------------------------------------------|\n| 1 | Country Code     | string   | ISO-3 alpha code                               | World Bank ISO-3 code                                |\n| 2 | IMF Country Code | int      | Numeric IMF country identifier                 | IMF country code                                     |\n| 3 | Country          | string   | 205 country / aggregate names                  | Country name in World Bank spelling                  |\n| 4 | Indicator Type   | string   | Inflation                                      | Constant within a sheet; useful when sheets stacked |\n| 5 | Series Name      | string   | e.g. Headline Consumer Price Inflation         | Series description                                   |\n| 6 – 60 | 1970 … 2024 | float    | Inflation rate in % year-on-year, may be blank | One column per year                                  |\n| 61 | Note            | string   | e.g. Annual average inflation                  | Methodology note                                     |\n\n#### Data Characteristics and Quality\n\n- **Coverage.** 205 countries, 4 CPI types used (Headline / Food / Energy / Core), 55 years (1970–2024). After melting to long format the indicator dataset has roughly 50,000 rows with non-missing inflation values.\n- **Missing values.** Coverage is shallowest before 1990 and for low-income countries; e.g. Food and Energy CPI series only begin in the 1990s for many emerging economies.\n- **Extreme values.** Inflation has very long tails: minimum –73 % (deflationary spikes), maximum 65,374 % (Venezuela 2018 hyperinflation). For visualisation we will clip or use a symlog axis; for statistical summaries we use medians.\n- **Country naming.** World Bank uses names like \"Egypt, Arab Rep.\" while UN Comtrade uses \"Egypt\". This is the main reason country_mapping.py and the in-script COUNTRY_MAP dictionary exist.\n\n::: {#cell-fig-cpi-distribution .cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\"}\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\ntrade = pd.read_csv(\"../data/processed/precious_metals_trade_1988_2024.csv\")\ncpi = trade[\"Headline CPI\"].dropna().clip(-10, 50)\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nax.hist(cpi, bins=60, color=\"#4C78A8\", edgecolor=\"white\")\nax.axvline(0, color=\"#888\", linewidth=0.8)\nax.set_xlabel(\"Headline CPI inflation (%)\")\nax.set_ylabel(\"Country–year–record count\")\nax.set_title(\"Headline CPI in the joined dataset (clipped)\")\nfor s in (\"top\", \"right\"):\n    ax.spines[s].set_visible(False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/var/folders/yg/7z2hqpxd2q3_f61kw91nbmj00000gn/T/ipykernel_39823/1211175549.py:15: UserWarning: The figure layout has changed to tight\n  plt.tight_layout()\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Distribution of annual Headline CPI inflation in the merged dataset, clipped to [-10, 50] % for readability. Values beyond the clip points (Zimbabwe, Venezuela, etc.) are real but flatten the histogram if left in.](data_report_files/figure-html/fig-cpi-distribution-output-2.png){#fig-cpi-distribution width=580 height=342}\n:::\n:::\n\n\n**Implications for visualisation.** The fat right tail reinforces the design choice in Beat 2 of the narrative: curate to a small, named set of high- and low-inflation countries rather than scatter the full panel. The shallow pre-1990 coverage is one of the reasons the visible narrative is scoped to 2017–2024 (see \"Scope of the visible narrative\" above), where the global panel is dense and balanced.\n\n## Processed Data\n\n### Overview Processed Datasets\n\n: Overview of processed datasets produced by data/build_dataset.py and data/country_mapping.py. {#tbl-processed-overview}\n\n| Name                                          | Source                                              | Storage location                                       | Rows     |\n|-----------------------------------------------|-----------------------------------------------------|--------------------------------------------------------|----------|\n| precious_metals_trade_1988_2024.csv           | Datasets 1 + 2 + 3 joined                           | data/processed/precious_metals_trade_1988_2024.csv     | 192,490  |\n| baci_gold_with_inflation.csv                  | UN Comtrade BACI extract (gold imports) + Dataset 3 | data/processed/baci_gold_with_inflation.csv            | 50,331   |\n| country_mapping.csv                           | All trade countries → ISO-2 codes                   | data/processed/country_mapping.csv                     | 191      |\n\n### Details Processed Dataset 1\n\n**Content.** The main analysis-ready table. One row per country × year × metal × flow, with the matching annual Headline CPI value joined in.\n\n**Processing steps** (see data/build_dataset.py for the exact code):\n\n1. Load the Kaggle UN Comtrade dump (1988–2016) and the UN Comtrade 1990–2025 extract.\n2. Filter to rows whose commodity description contains \"Gold\", \"Silver\", \"Platinum\", or \"precious metal\" (case-insensitive).\n3. Classify each row into one of four metal groups: Gold, Silver, Platinum, or Other precious.\n4. Rename and project to seven analysis columns: country, year, metal group, flow, trade value in USD, weight in kg, and optionally HS category.\n5. Load four annual inflation sheets (hcpi_a, fcpi_a, ecpi_a, ccpi_a) from Inflation-data.xlsx, reshape from wide to long, drop missing rates.\n6. Apply a 30-entry COUNTRY_MAP to harmonise country names between the two sources (e.g. \"Russian Federation\" → \"Russia\", \"Czechia\" → \"Czech Republic\").\n7. Pivot inflation back to wide so each indicator becomes its own column, then left-join on country and year.\n8. Persist to CSV. Final Headline CPI match rate: **85.1 %** of trade rows.\n\n**Access.** Regenerable from data/raw/ with `python data/build_dataset.py`. The CSV is small enough (~10 MB) to commit and read in-memory.\n\n#### Data Catalogue\n\n: Data catalogue for precious_metals_trade_1988_2024.csv. {#tbl-processed-catalogue}\n\n| # | Column name      | Datatype | Values / range                                | Description                                                  |\n|---|------------------|----------|------------------------------------------------|--------------------------------------------------------------|\n| 1 | country          | string   | 263 unique names                               | Reporting country, harmonised name                           |\n| 2 | year             | int      | 1988 – 2024                                    | Trade reporting year                                         |\n| 3 | metal_group      | category | Gold, Silver, Platinum, Other precious         | Collapsed metal class                                        |\n| 4 | flow             | category | Import, Export, Re-Import, Re-Export           | Direction                                                    |\n| 5 | trade_value_usd  | int      | 1 – 9.7 × 10¹⁰                                 | Trade value in current US dollars                            |\n| 6 | weight_kg        | float    | 0 – 1.6 × 10⁹, ~11 % missing                   | Net weight                                                   |\n| 7 | Headline CPI     | float    | –73 – 65,374, ~15 % missing                    | Annual Headline CPI inflation (%)                            |\n\nThe schema is intentionally narrow (six categorical and numerical analysis columns) to keep the Streamlit app responsive.\n\n#### Data Characteristics and Quality\n\n::: {#tbl-quality .cell tbl-cap='Per-column missing / zero rates and basic ranges for the main processed dataset.' execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\nimport pandas as pd\n\ntrade = pd.read_csv(\"../data/processed/precious_metals_trade_1988_2024.csv\")\nn = len(trade)\n\nsummary = pd.DataFrame({\n    \"n_missing\":  trade.isna().sum(),\n    \"pct_missing\": (trade.isna().mean() * 100).round(1),\n    \"n_zero\": (trade.select_dtypes(\"number\") == 0).sum().reindex(trade.columns).fillna(0).astype(int),\n    \"min\": trade.select_dtypes(\"number\").min().reindex(trade.columns),\n    \"max\": trade.select_dtypes(\"number\").max().reindex(trade.columns),\n})\nsummary\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>n_missing</th>\n      <th>pct_missing</th>\n      <th>n_zero</th>\n      <th>min</th>\n      <th>max</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>country</th>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>year</th>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0</td>\n      <td>1988.000000</td>\n      <td>2.024000e+03</td>\n    </tr>\n    <tr>\n      <th>metal_group</th>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>flow</th>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>trade_value_usd</th>\n      <td>0</td>\n      <td>0.0</td>\n      <td>0</td>\n      <td>1.000000</td>\n      <td>9.696865e+10</td>\n    </tr>\n    <tr>\n      <th>weight_kg</th>\n      <td>20479</td>\n      <td>10.6</td>\n      <td>16745</td>\n      <td>0.000000</td>\n      <td>1.640361e+09</td>\n    </tr>\n    <tr>\n      <th>Headline CPI</th>\n      <td>28750</td>\n      <td>14.9</td>\n      <td>58</td>\n      <td>-72.728996</td>\n      <td>6.537408e+04</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nKey takeaways:\n\n- **No duplicates** on the natural key of country, year, metal group and flow, verified during build.\n- **Inflation join rate** is 85 % overall; the unmatched 15 % is overwhelmingly micro-states and territories (e.g. Cook Islands, Falkland Islands) absent from the World Bank database, acceptable for a global story.\n- **Country mismatch residual.** After the manual country mapping, ~14 small trade entities still have no inflation partner; they are kept in the dataset with a missing Headline CPI but excluded from inflation-conditional charts at render time.\n- **Outliers.** A handful of country-year cells exceed 10 bn USD in gold trade (Switzerland 2011–2014, UK 2010–2014). These are real refining-hub flows, not data errors. They are *not* shown in the visible narrative (which is scoped to 2017–2024), but the same refining-hub pattern continues post-2017 with even larger values (Switzerland imports about 100 bn USD of gold per year in the 2020 to 2024 window), so the outliers are kept in the processed CSV for reproducibility.\n\n**Implications.** Coverage and quality are sufficient for all five beats of the scrollytelling narrative. The two design decisions actually forced by the data are: (i) **scope the visible narrative to 2017–2024**, because the pre-2017 panel is missing major reporters (Switzerland, USA, UK, UAE) and would yield a misleading aggregate; and (ii) **curate the inflation-vs-imports comparison (Beat 2) to ten named countries** rather than plot the full panel, because the curated set lands the disconfirmation that the beat exists to make.\n\n### Details Processed Dataset 2\n\n**Content.** Country-year gold *imports* only, drawn from a BACI-style harmonisation of UN Comtrade for 2017–2024, joined with Headline CPI.\n\n**Reason it exists.** This dataset was prepared for an earlier draft of the narrative that used an inflation-vs-gold-imports scatter. The current scrollytelling app does not use it. Every visible beat is built from Processed Dataset 1 filtered to 2017 to 2024. The file is kept in `data/processed/` as a build artefact and as a smaller, pre-aggregated frame any future iteration can pick up from, but it is not referenced by `deployment/app.py`.\n\n**Processing.** Filter to Gold imports only on the 1990–2025 UN Comtrade extract, then left-join Headline CPI on country and year. Same naming-harmonisation as Dataset 1.\n\n#### Data Catalogue\n\nSame schema as Dataset 1, but restricted to gold imports. Year range 2017–2024.\n\n#### Data Characteristics and Quality\n\n50,331 rows over 224 countries. Headline CPI is missing for ~11 % of rows (same micro-state pattern as the main dataset). No further cleaning is applied. This is a view onto the joined data, not a new pipeline.\n\n### Details Processed Dataset 3\n\n**Content.** Two-column lookup table mapping every country name appearing in the trade data to an ISO-3166 alpha-2 code, used for choropleth rendering in Plotly (which expects ISO codes, not names).\n\n**Processing.** Generated by data/country_mapping.py using a three-step strategy:\n\n1. Exact match against the pycountry library by name.\n2. Fuzzy fallback via pycountry's fuzzy search.\n3. Manual overrides for ~30 known mismatches (\"Korea, Rep.\" → KR, \"Hong Kong SAR, China\" → HK, etc.).\n\n**Quality.** 191 of 263 distinct country strings map to a valid ISO-2 code. The remaining ~70 are sub-national entities, historical aggregates (\"Fmr Sudan\", \"Neth. Antilles\") or non-country reporters (\"Other Asia, nes\", \"Bunkers\"); they appear in the trade data but are not plottable on a country map and are filtered out of choropleths.\n\n#### Data Catalogue\n\n: Data catalogue for country_mapping.csv. {#tbl-country-mapping}\n\n| # | Column name | Datatype | Values                                    | Description                          |\n|---|-------------|----------|-------------------------------------------|--------------------------------------|\n| 1 | country     | string   | 191 distinct names                        | Country name as it appears in trade  |\n| 2 | iso_code    | string   | ISO-3166-1 alpha-2 (e.g. CH, US, IN)      | Country ISO-2 code                   |\n\n",
    "supporting": [
      "data_report_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}