project:
  type: website
  output-dir: build
  render:
    - project_charta.qmd
    - data_report.qmd

lang: en

website:
  title: "Follow the Gold"
  search: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - project_charta.qmd
      - data_report.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

number-sections: true

jupyter: python3

execute:
  freeze: auto

editor:
  render-on-save: true
